### PR TITLE
Add support for methods in now.json config

### PR DESCRIPTION
**Pull request by damack**
It's also possible to have methods in the now.json config. Which is currenly not supported. I added this support.

### CODE REVIEW

**Comment by krasimir** [comment]
Thank you for submitting the PR. Can you please incorporate an example here https://github.com/krasimir/now-lambda-runner/tree/master/example I want to reproduce your use case locally.

**Comment by damack** [comment]
I changed the example and i hope this helps

**Comment by krasimir** [comment]
Thanks. Now I see what you meant.

**Comment by krasimir** [comment]
`2.1.0` version released.

**Pull request merged**
